version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 40
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
    - 14.14.31
  - dependency-name: "@angular/language-service"
    versions:
    - 11.0.5
    - 11.1.1
    - 11.2.3
  - dependency-name: core-js
    versions:
    - 3.8.1
    - 3.8.3
    - 3.9.1
  - dependency-name: karma
    versions:
    - 5.2.3
    - 6.0.4
    - 6.1.1
  - dependency-name: rxjs
    versions:
    - 6.6.6
  - dependency-name: primeng
    versions:
    - 11.0.0
    - 11.2.0
    - 11.2.3
  - dependency-name: "@types/jasmine"
    versions:
    - 3.6.2
    - 3.6.3
    - 3.6.4
  - dependency-name: "@angular/cli"
    versions:
    - 11.0.5
    - 11.1.2
    - 11.2.2
  - dependency-name: "@angular-devkit/build-angular"
    versions:
    - 0.901.13
